### ISSUE TITLE
Cannot find module './translations/localize' when updating from 1.7.1 to 1.9

### ISSUE THREAD

**Issue by reptilex** [custom-cards/custom-card-helpers#60]
When I try to update custom-card-helper package I get an error:
`Cannot find module './translations/localize' or its corresponding type declarations.

2 import { LocalizeFunc } from "./translations/localize";`

This are my packages and my update instruction:
<img width="956" alt="Screenshot 2022-04-02 at 12 44 04" src="https://user-images.githubusercontent.com/8057797/161379608-6e69164f-ad0d-4a25-b144-6f8b084c0f89.png">

It seems it requires an update on typescript and this may lead to the error. My packages after the update are:
<img width="964" alt="Screenshot 2022-04-02 at 12 45 03" src="https://user-images.githubusercontent.com/8057797/161379646-bc3d3e10-d07b-47e0-a718-d2b5597b5a48.png">

I know this might be very specific to what I have here, but could you at least point me into the right direction? I suffer with all this typescript babel package stuff. Thanks

**Comment by reptilex** [comment]
I can update everything red but custom card helpers without any issues:
<img width="965" alt="Screenshot 2022-04-02 at 12 57 13" src="https://user-images.githubusercontent.com/8057797/161380131-eb395d7d-d3f5-4efa-8cde-48782dea8779.png">
